/**
 * Build-time script: generates src/shared/pwa/surahPageMap.ts
 *
 * Reads 604 mushaf layout JSONs from data/mushaf-layout/mushaf/
 * and produces a TypeScript source file with the SURAH_PAGE_MAP constant.
 *
 * Run with: npx tsx scripts/generate-surah-map.ts
 */

import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Word {
  location: string;
  [key: string]: unknown;
}

interface Line {
  type: string;
  words?: Word[];
  [key: string]: unknown;
}

interface PageLayout {
  page: number;
  lines: Line[];
}

interface SurahPageEntry {
  readonly startPage: number;
  readonly endPage: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function parseSurahId(location: string): number | null {
  const parts = location.split(":");
  if (parts.length < 1) return null;
  const id = parseInt(parts[0], 10);
  return Number.isFinite(id) && id >= 1 && id <= 114 ? id : null;
}

function extractSurahIdsFromPage(layout: PageLayout): ReadonlySet<number> {
  const ids = new Set<number>();
  for (const line of layout.lines) {
    if (!Array.isArray(line.words)) continue;
    for (const word of line.words) {
      const id = parseSurahId(word.location);
      if (id !== null) ids.add(id);
    }
  }
  return ids;
}

function readLayoutFile(filePath: string): PageLayout {
  const raw = fs.readFileSync(filePath, "utf-8");
  const parsed: unknown = JSON.parse(raw);
  if (
    typeof parsed !== "object" ||
    parsed === null ||
    !("page" in parsed) ||
    !("lines" in parsed)
  ) {
    throw new Error(`Invalid layout file: ${filePath}`);
  }
  return parsed as PageLayout;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function buildSurahPageMap(): Record<number, SurahPageEntry> {
  const projectRoot = path.resolve(path.dirname(process.argv[1]), "..");
  const layoutDir = path.join(
    projectRoot,
    "data",
    "mushaf-layout",
    "mushaf"
  );

  const files = fs
    .readdirSync(layoutDir)
    .filter((f) => /^page-\d{3}\.json$/.test(f))
    .sort();

  if (files.length !== 604) {
    throw new Error(
      `Expected 604 layout files, found ${files.length}. Check data/mushaf-layout/mushaf/.`
    );
  }

  // surahId -> { minPage, maxPage }
  const accumulator: Record<number, { minPage: number; maxPage: number }> = {};

  for (const filename of files) {
    const filePath = path.join(layoutDir, filename);
    const layout = readLayoutFile(filePath);
    const pageNumber = layout.page;
    const surahIds = extractSurahIdsFromPage(layout);

    for (const id of surahIds) {
      const current = accumulator[id];
      if (current === undefined) {
        accumulator[id] = { minPage: pageNumber, maxPage: pageNumber };
      } else {
        accumulator[id] = {
          minPage: Math.min(current.minPage, pageNumber),
          maxPage: Math.max(current.maxPage, pageNumber),
        };
      }
    }
  }

  const surahCount = Object.keys(accumulator).length;
  if (surahCount !== 114) {
    throw new Error(
      `Expected 114 surahs, found ${surahCount}. Data may be incomplete.`
    );
  }

  for (let id = 1; id <= 114; id++) {
    const entry = accumulator[id];
    if (entry === undefined || entry.minPage === 0 || entry.maxPage === 0) {
      throw new Error(`Surah ${id} has zero pages or was not found in layout data.`);
    }
  }

  const result: Record<number, SurahPageEntry> = {};
  for (let id = 1; id <= 114; id++) {
    const entry = accumulator[id];
    result[id] = { startPage: entry.minPage, endPage: entry.maxPage };
  }
  return result;
}

function generateTypeScriptSource(
  map: Record<number, SurahPageEntry>
): string {
  const entries = Object.entries(map)
    .map(([id, entry]) => `  ${id}: { startPage: ${entry.startPage}, endPage: ${entry.endPage} },`)
    .join("\n");

  return `/**
 * Auto-generated by scripts/generate-surah-map.ts
 * DO NOT EDIT MANUALLY — re-run the generator to update.
 *
 * Maps each surah ID (1–114) to its page range in the Uthmani mushaf (604 pages).
 */

export interface SurahPageEntry {
  readonly startPage: number;
  readonly endPage: number;
}

export const SURAH_PAGE_MAP: Readonly<Record<number, SurahPageEntry>> = {
${entries}
} as const;

/**
 * Returns the surah ID that contains the given page number.
 * When multiple surahs share a page, returns the highest-numbered (last) surah
 * that starts on or before that page, which is the most specific match.
 */
export function getPageSurahId(pageNumber: number): number | undefined {
  for (let id = 114; id >= 1; id--) {
    const entry = SURAH_PAGE_MAP[id];
    if (entry && pageNumber >= entry.startPage && pageNumber <= entry.endPage) {
      return id;
    }
  }
  return undefined;
}

/**
 * Returns the number of pages occupied by the given surah.
 */
export function getSurahPageCount(surahId: number): number | undefined {
  const entry = SURAH_PAGE_MAP[surahId];
  if (!entry) return undefined;
  return entry.endPage - entry.startPage + 1;
}
`;
}

function main(): void {
  console.log("Building surah-to-page map from layout JSONs…");
  const map = buildSurahPageMap();

  const projectRoot = path.resolve(path.dirname(process.argv[1]), "..");
  const outputPath = path.join(projectRoot, "src", "shared", "pwa", "surahPageMap.ts");

  const source = generateTypeScriptSource(map);
  fs.writeFileSync(outputPath, source, "utf-8");

  console.log(`Written to: ${outputPath}`);
  console.log(`Surahs mapped: ${Object.keys(map).length}`);
  console.log(`Surah 1: pages ${map[1].startPage}–${map[1].endPage}`);
  console.log(`Surah 2: pages ${map[2].startPage}–${map[2].endPage}`);
  console.log(`Surah 114: pages ${map[114].startPage}–${map[114].endPage}`);
}

main();
